### ISSUE TITLE
 https://github.com/RiemaLabs/nubit-cli.git repository 404

### ISSUE THREAD

**Issue by luoyechao** [RiemaLabs/modular-indexer-committee#53]
I want to build a nubit-cli，but I can't find the nubit-cli repository. When will the repository open ?

**Comment by TianyueLi1227** [comment]
Hello luoyechao, Thank you for reaching out. As of now, `nubit-cli` has not been released to the public. We are diligently working on it to ensure the best possible experience to our users. Please keep an eye on our Github site for the latest information.
